[2022-11-20 21:33:56,202] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v4.sensor_minio_s3 manual__2022-11-20T21:33:55.498634+00:00 [queued]>
[2022-11-20 21:33:56,211] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v4.sensor_minio_s3 manual__2022-11-20T21:33:55.498634+00:00 [queued]>
[2022-11-20 21:33:56,212] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 21:33:56,212] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2022-11-20 21:33:56,213] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 21:33:56,222] {taskinstance.py:1259} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2022-11-20 21:33:55.498634+00:00
[2022-11-20 21:33:56,225] {standard_task_runner.py:52} INFO - Started process 4757 to run task
[2022-11-20 21:33:56,227] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_minio_s3_v4', 'sensor_minio_s3', 'manual__2022-11-20T21:33:55.498634+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpf4_bcaz3', '--error-file', '/tmp/tmpnpwk0z1y']
[2022-11-20 21:33:56,229] {standard_task_runner.py:77} INFO - Job 14: Subtask sensor_minio_s3
[2022-11-20 21:33:56,277] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_with_minio_s3_v4.sensor_minio_s3 manual__2022-11-20T21:33:55.498634+00:00 [running]> on host 412505171ea9
[2022-11-20 21:33:56,321] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=charlie
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v4
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T21:33:55.498634+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T21:33:55.498634+00:00
[2022-11-20 21:33:56,322] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:33:56,323] {base_aws.py:401} INFO - Airflow Connection: aws_conn_id=mino_conn
[2022-11-20 21:33:56,331] {base_aws.py:181} INFO - Credentials retrieved from extra_config
[2022-11-20 21:33:56,332] {base_aws.py:93} INFO - Creating session with aws_access_key_id=AKIAIOSFODNN7EXAMPLE region_name=None
[2022-11-20 21:33:56,345] {base_aws.py:168} INFO - role_arn is None
[2022-11-20 21:33:56,350] {logging_mixin.py:109} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py:494 DeprecationWarning: client_type is deprecated. Set client_type from class attribute.
[2022-11-20 21:34:01,394] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:06,406] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:11,396] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:16,414] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:21,420] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:26,433] {s3_key.py:96} INFO - Poking for key : s3://airflow/data.csv
[2022-11-20 21:34:26,439] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 240, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: dag_with_minio_s3_v4
[2022-11-20 21:34:26,455] {taskinstance.py:1277} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_with_minio_s3_v4, task_id=sensor_minio_s3, execution_date=20221120T213355, start_date=20221120T213356, end_date=20221120T213426
[2022-11-20 21:34:26,471] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task sensor_minio_s3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 240, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: dag_with_minio_s3_v4
[2022-11-20 21:34:26,510] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-20 21:34:26,538] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
