[2022-11-15T18:40:47.823+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2022-11-15T18:40:47.839+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2022-11-15T18:40:47.841+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-15T18:40:47.842+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-15T18:40:47.843+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-15T18:40:47.865+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2022-11-13 00:00:00+00:00
[2022-11-15T18:40:47.871+0000] {standard_task_runner.py:55} INFO - Started process 768 to run task
[2022-11-15T18:40:47.876+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_dependencies_v2', 'get_matplotlib', 'scheduled__2022-11-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpt_z7bau6']
[2022-11-15T18:40:47.882+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask get_matplotlib
[2022-11-15T18:40:48.017+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_python_dependencies_v2.get_matplotlib scheduled__2022-11-13T00:00:00+00:00 [running]> on host 927c3d249f0b
[2022-11-15T18:40:48.145+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=charlie
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v2
AIRFLOW_CTX_TASK_ID=get_matplotlib
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-13T00:00:00+00:00
[2022-11-15T18:40:48.148+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 16, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2022-11-15T18:40:48.168+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_python_dependencies_v2, task_id=get_matplotlib, execution_date=20221113T000000, start_date=20221115T184047, end_date=20221115T184048
[2022-11-15T18:40:48.185+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task get_matplotlib (No module named 'matplotlib'; 768)
[2022-11-15T18:40:48.212+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-15T18:40:48.239+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
