[2022-11-13T17:06:28.135+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-13T17:06:28.157+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-13T17:06:28.158+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-13T17:06:28.159+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 6
[2022-11-13T17:06:28.160+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-13T17:06:28.190+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-11-10 00:00:00+00:00
[2022-11-13T17:06:28.196+0000] {standard_task_runner.py:55} INFO - Started process 2840 to run task
[2022-11-13T17:06:28.217+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v1', 'create_postgres_table', 'scheduled__2022-11-10T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpgj908hcc']
[2022-11-13T17:06:28.254+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask create_postgres_table
[2022-11-13T17:06:28.393+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-11-10T00:00:00+00:00 [running]> on host 6a6c6e07e37b
[2022-11-13T17:06:28.513+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=charlie
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T00:00:00+00:00
[2022-11-13T17:06:28.542+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2022-11-13T17:06:28.548+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221110T000000, start_date=20221113T170628, end_date=20221113T170628
[2022-11-13T17:06:28.565+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task create_postgres_table (The conn_id `postgres_localhost` isn't defined; 2840)
[2022-11-13T17:06:28.545+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-13T17:06:28.581+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
